run:
  timeout: 10m

linters:
  disable-all: false
  enable:
    - misspell
    - gocognit

linters-settings:
  gocognit:
    # Minimal code complexity to report
    # Default: 30 (but we recommend 10-20)
    min-complexity: 30
